### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by geftimov** [Seishin/showcaseview-android#1]
Hi,

I like the library. Congrats.
Do you intent to upload it to maven?

**Comment by Seishin** [comment]
Hello geftimov!

Thanks for your interest in this library project! 
Sure! It will be moved in a maven repo when it fulfills most of its basic functionalities and become more stable.

**Comment by Seishin** [comment]
Hello, @geftimov! 

I would like to inform you that the project is uploaded to Maven and you could add it as a dependency:

``` java
compile 'co.naughtyspirit:showcaseview-library:0.0.1'
```

Best regards!
