### ISSUE TITLE
Question: Is this a fork to the ShowcaseView repo by amlcurran?

### ISSUE THREAD

**Issue by hy9be** [Seishin/showcaseview-android#7]
https://github.com/amlcurran/ShowcaseView

I run into some issues when using the original ShowcaseView library. So I am wondering if this repo is a fork. Thanks!

**Comment by Seishin** [comment]
Hello! 

Nope. It's not a fork but it uses some ideas from the pointed library. 

Greetings!

**Comment by hy9be** [comment]
Got it. Thanks! I will give it a try.
